import { describe, it, expect, vi, beforeEach } from 'vitest';
import { SqlitePhotoRepository, type SqlDb } from './sqlite-photo.repository.js';
import type { CreatePhoto } from '../models/photo.types.js';

/**
 * Mock simple de SqlDb para tests de fotos.
 */
function createMockDb(): SqlDb {
  let rows: Record<string, unknown>[] = [];

  return {
    execute: vi.fn((sql: string, params?: unknown[]) => {
      const upper = sql.trim().toUpperCase();
      if (upper.startsWith('CREATE')) {
        return Promise.resolve({ rowsAffected: 0 });
      }
      if (upper.startsWith('INSERT')) {
        // Use the ID generated by the repository (first param)
        rows.push({
          id: params?.[0],
          route_id: params?.[1],
          file_path: params?.[2],
          latitude: params?.[3],
          longitude: params?.[4],
          captured_at: params?.[5],
          created_at: params?.[6] ?? new Date().toISOString(),
        });
        return Promise.resolve({ rowsAffected: 1 });
      }
      if (upper.startsWith('DELETE')) {
        const id = params?.[0] as string;
        rows = rows.filter((r) => r.id !== id && r.route_id !== id);
        return Promise.resolve({ rowsAffected: 1 });
      }
      if (upper.startsWith('UPDATE PHOTOS SET REMOTE_PHOTO_ID')) {
        const [remotePhotoId, id] = params as [string, string];
        const row = rows.find((r) => r.id === id);
        if (row) row.remote_photo_id = remotePhotoId;
        return Promise.resolve({ rowsAffected: row ? 1 : 0 });
      }
      return Promise.resolve({ rowsAffected: 0 });
    }),
    select: vi.fn((sql: string, params?: unknown[]) => {
      const upper = sql.trim().toUpperCase();
      let result = [...rows];

      // Filtro por route_id (WHERE route_id = ?)
      if (params?.length === 1 && upper.includes('ROUTE_ID')) {
        const routeId = params[0] as string;
        result = result.filter((r) => r.route_id === routeId);
      }
      // Filtro por id (WHERE id = ?, sin route_ prefix)
      else if (params?.length === 1 && upper.includes('WHERE ID =')) {
        const id = params[0] as string;
        result = result.filter((r) => r.id === id);
      }

      // Ordenar por captured_at DESC
      if (upper.includes('ORDER BY')) {
        result.sort((a, b) => String(b.captured_at).localeCompare(String(a.captured_at)));
      }

      // COUNT
      if (upper.includes('COUNT')) {
        return Promise.resolve([{ count: result.length }]);
      }

      return Promise.resolve(result);
    }),
  };
}

function makeCreatePhoto(overrides?: Partial<CreatePhoto>): CreatePhoto {
  return {
    routeId: 'route-1',
    filePath: '/photos/photo-1.jpg',
    latitude: 40.416775,
    longitude: -3.70379,
    capturedAt: new Date().toISOString(),
    ...overrides,
  };
}

describe('SqlitePhotoRepository', () => {
  let db: SqlDb;
  let repo: SqlitePhotoRepository;

  beforeEach(() => {
    db = createMockDb();
    repo = new SqlitePhotoRepository(db);
  });

  it('should create the photos table on first call', async () => {
    await repo.add(makeCreatePhoto());
    expect(db.execute).toHaveBeenCalledWith(
      expect.stringContaining('CREATE TABLE IF NOT EXISTS photos'),
    );
  });

  it('should add a photo and return it with id', async () => {
    const photo = await repo.add(makeCreatePhoto());
    expect(photo.id).toBeDefined();
    expect(photo.routeId).toBe('route-1');
    expect(photo.filePath).toBe('/photos/photo-1.jpg');
    expect(photo.latitude).toBe(40.416775);
    expect(photo.longitude).toBe(-3.70379);
    expect(photo.createdAt).toBeDefined();
  });

  it('should get photos by route id ordered by captured_at desc', async () => {
    const now = new Date();
    const earlier = new Date(now.getTime() - 60000);

    await repo.add(makeCreatePhoto({ capturedAt: now.toISOString() }));
    await repo.add(makeCreatePhoto({ capturedAt: earlier.toISOString() }));
    await repo.add(makeCreatePhoto({ capturedAt: now.toISOString(), routeId: 'other-route' }));

    const photos = await repo.getByRouteId('route-1');

    expect(photos).toHaveLength(2);
    // Should be ordered by captured_at desc
    expect(new Date(photos[0]!.capturedAt).getTime()).toBeGreaterThanOrEqual(
      new Date(photos[1]!.capturedAt).getTime(),
    );
  });

  it('should get a photo by id', async () => {
    const added = await repo.add(makeCreatePhoto());
    const found = await repo.getById(added.id);
    expect(found).not.toBeNull();
    expect(found!.id).toBe(added.id);
  });

  it('should return null if photo not found by id', async () => {
    const found = await repo.getById('non-existent');
    expect(found).toBeNull();
  });

  it('should delete a photo by id', async () => {
    const added = await repo.add(makeCreatePhoto());
    await repo.delete(added.id);
    const found = await repo.getById(added.id);
    expect(found).toBeNull();
  });

  it('should count photos by route id', async () => {
    await repo.add(makeCreatePhoto());
    await repo.add(makeCreatePhoto());
    await repo.add(makeCreatePhoto({ routeId: 'other-route' }));

    const count = await repo.countByRouteId('route-1');
    expect(count).toBe(2);
  });

  it('should return empty array for route with no photos', async () => {
    const photos = await repo.getByRouteId('empty-route');
    expect(photos).toEqual([]);
  });

  it('should return 0 count for route with no photos', async () => {
    const count = await repo.countByRouteId('empty-route');
    expect(count).toBe(0);
  });

  it('should use parameterized queries', () => {
    expect(db.execute).toBeDefined();
    expect(db.select).toBeDefined();
    // The mock itself enforces parameterized queries by only matching
    // calls that include params — safe by construction in this test pattern.
  });

  it('should initialize remotePhotoId to null on add', async () => {
    const photo = await repo.add(makeCreatePhoto());
    expect(photo.remotePhotoId).toBeNull();
  });

  it('markPhotoSynced() persists the remote id and getById/getByRouteId reflect it', async () => {
    const added = await repo.add(makeCreatePhoto());

    await repo.markPhotoSynced(added.id, 'remote-photo-1');

    const byId = await repo.getById(added.id);
    expect(byId?.remotePhotoId).toBe('remote-photo-1');
    const byRoute = await repo.getByRouteId('route-1');
    expect(byRoute[0]?.remotePhotoId).toBe('remote-photo-1');
  });
});

/**
 * Mock dedicado para el mecanismo de migración de columna `remote_photo_id`
 * -- mismo patrón que `remote_photo_id column migration` de
 * `sqlite-route.repository.spec.ts` (el mock compartido de arriba no modela
 * `PRAGMA table_info`).
 */
function createMigrationMockDb(hasRemotePhotoIdColumn: boolean): { db: SqlDb; alterTableCalls: string[] } {
  const alterTableCalls: string[] = [];
  const columnInfo = hasRemotePhotoIdColumn
    ? [{ name: 'id' }, { name: 'route_id' }, { name: 'remote_photo_id' }]
    : [{ name: 'id' }, { name: 'route_id' }];
  const preexistingRow = {
    id: 'legacy-photo-1', route_id: 'route-1', file_path: '/photos/legacy.jpg', latitude: null, longitude: null,
    captured_at: '2026-01-01T00:00:00.000Z', created_at: '2026-01-01T00:00:00.000Z',
  };

  return {
    alterTableCalls,
    db: {
      execute: vi.fn((sql: string) => {
        const upper = sql.trim().toUpperCase();
        if (upper.startsWith('ALTER TABLE')) alterTableCalls.push(sql.trim());
        return Promise.resolve({ rowsAffected: 0 });
      }),
      select: vi.fn((sql: string) => {
        const upper = sql.trim().toUpperCase();
        if (upper.startsWith('PRAGMA TABLE_INFO')) return Promise.resolve(columnInfo);
        if (upper.startsWith('SELECT * FROM PHOTOS')) return Promise.resolve([{ ...preexistingRow }]);
        return Promise.resolve([]);
      }),
    },
  };
}

describe('remote_photo_id column migration', () => {
  it('runs ALTER TABLE exactly once when remote_photo_id is missing from a preexisting photos table, keeping the existing row intact', async () => {
    const { db, alterTableCalls } = createMigrationMockDb(false);
    const repo = new SqlitePhotoRepository(db);

    const all = await repo.getByRouteId('route-1');

    expect(alterTableCalls).toEqual(['ALTER TABLE photos ADD COLUMN remote_photo_id TEXT;']);
    expect(all).toHaveLength(1);
    expect(all[0]!.id).toBe('legacy-photo-1');
    expect(all[0]!.remotePhotoId).toBeNull();
  });

  it('does not run ALTER TABLE when remote_photo_id already exists', async () => {
    const { db, alterTableCalls } = createMigrationMockDb(true);
    const repo = new SqlitePhotoRepository(db);

    await repo.getByRouteId('route-1');

    expect(alterTableCalls).toHaveLength(0);
  });

  it('runs the migration exactly once when two callers race on the same shared repository instance', async () => {
    const { db, alterTableCalls } = createMigrationMockDb(false);
    const repo = new SqlitePhotoRepository(db);

    await Promise.all([repo.getByRouteId('route-1'), repo.getByRouteId('route-1')]);

    expect(alterTableCalls).toHaveLength(1);
  });
});